name: dedo
description: "A new Flutter project."
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies
dependencies:
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.6
  equatable: ^2.0.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_timezone: ^4.1.0
  font_awesome_flutter: ^10.8.0
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # --------------- LOCAL FONTS ------------------ #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
